# Default values for guestbook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

services:
  backend:
    dbUrl: "mongodb:27017"
    replicaCount: 1 
    image:
      repository: guestbook-backend
      pullPolicy: IfNotPresent
      tag: "1.0.0"
    service:
      type: ClusterIP
      port: 8000
    ingress:
      enabled: true
      hosts:
      - host: be.ng.chuka.dev
        paths: 
          path: /
      annotations: {}
      tls: 
        enabled: true
        hosts:
        - be.ng.chuka.dev
  frontend:
    replicaCount: 1 
    image:
      repository: guestbook-frontend
      pullPolicy: IfNotPresent
      tag: "1.0.0"
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      hosts:
      - host: fe.ng.chuka.dev
        paths: 
          path: /
      annotations: {}
      tls: 
        enabled: false
        hosts:
        - fe.ng.chuka.dev

nameOverride: ""
fullnameOverride: ""

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod